# kind-cluster-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."ghcr.io".tls]
        insecure_skip_verify = true
kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    serverTLSBootstrap: true

nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
      listenAddress: "0.0.0.0"
    - containerPort: 443
      hostPort: 443
      protocol: TCP
      listenAddress: "0.0.0.0"
