apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-coll-basic-config
  namespace: opentelemetry
  labels:
    app: otel-coll-basic
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:

    exporters:
      debug:
        verbosity: detailed

      otlp/tempo:
        endpoint: tempo.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
    
    extensions:
      zpages:

    service:
      extensions: [zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo, debug]
