apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-coll-basic
  namespace: opentelemetry
  labels:
    app: otel-coll-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-coll-basic
  template:
    metadata:
      labels:
        app: otel-coll-basic
    spec:
      containers:
        - name: otel-coll-basic
          image:  otel/opentelemetry-collector-contrib:latest
          command:
            - "/otelcol-contrib"
            - "--config=/etc/otel/collector-config.yaml"
          ports:
            - containerPort: 4317 # gRPC receiver
            - containerPort: 4318 # HTTP receiver
            - containerPort: 55679 # zpages extensions
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel
      volumes:
        - name: otel-config
          configMap:
            name: otel-coll-basic-config
