apiVersion: v1
kind: Service
metadata:
  name: otel-coll-basic
  namespace: opentelemetry
  labels:
    app: otel-coll-basic
spec:
  ports:
    - port: 4317
      name: otlp-grpc
    - port: 4318
      name: otlp-http
    - port: 55679
      name: zpages
  selector:
    app: otel-coll-basic
